on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: 21 3 * * 3

name: Update list of workbench repos

jobs:
  collect-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: local::.
      - run: |
          workbench.analysis::find_workbench_repos("data/repos_workbench.json")
        shell: Rscript {0}
      - name: Save data
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add data/repos_workbench.json
          git commit -m "Update list of repos using workfbench" || echo "No changes to commit"
          git pull --rebase origin main
          git push