on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: 21 3 * * 3

name: Render and Publish

jobs:
  collect-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: local::.
      - run: |
          workbench.analysis::find_workbench_repos("data/repos_workbench.json")
        shell: Rscript {0}
      - name: Save data
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add data/repos_workbench.json
          git commit -m "Update list of repos using workfbench" || echo "No changes to commit"
          git pull --rebase origin main
          git push

  build-deploy:
    runs-on: ubuntu-latest
    needs: collect-repos
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - run: |
          sudo apt-get update
          sudo apt-get install -y libmagick++-dev

      - uses: r-lib/actions/setup-renv@v2

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
